<div class="sec_wrapper">

<div class="generic_box_no_color">
<b>DISCLAIMER AND LIMITATION OF LIABILITY</b> <br/>
  
 
 TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES, CONDITIONS AND REPRESENTATIONS WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, RELATING IN ANY WAY TO THIS WEB SITE, YOUR USE OF THIS WEB SITE AND THE INFORMATION, PRODUCTS AND SERVICES SUPPLIED, OFFERED TO BE SUPPLIED OR ADVERTISED OR ACCESSED THROUGH THIS WEB SITE; AND LIABILITY (INCLUDING FOR NEGLIGENCE) TO YOU OR ANYONE ELSE IN RESPECT OF ANY LOSS OR DAMAGE (INCLUDING SPECIAL, INDIRECT OR CONSEQUENTIAL LOSS OR DAMAGE), COSTS AND EXPENSES SUFFERED BY YOU OR CLAIMS MADE AGAINST YOU ARISING FROM OR IN CONNECTION WITH ANY USE OF THE INFORMATION, PRODUCTS OR SERVICES SUPPLIED, OFFERED TO BE SUPPLIED OR ADVERTISED OR ACCESSED THROUGH THIS WEB SITE FOR ANY REASON WHATSOEVER (INCLUDING NEGLIGENCE).
 
 </div>
</div>